import { CheckCircleFilled, ClockCircleOutlined, EyeOutlined, LockOutlined, SafetyCertificateOutlined, StopOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Col, Empty, List, Modal, Row, Statistic, Switch, Tag, Typography, message } from 'antd'
import dayjs from 'dayjs'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { createDataConsent, getAgentApprovals, getAuthorizationAccessLogs, getAuthorizationOverview, getAuthorizationScopes, getDataConsents, revokeDataConsent, type AgentApproval, type AuthorizationAccessLog, type AuthorizationOverview, type DataConsent, type DataScope } from '../../api/dataAuthorizations'
import './data-authorization.css'

const { Text } = Typography
const AI_SCOPES = ['health_profile.read', 'wearable.sleep.read', 'wearable.exercise.read', 'wearable.heart_rate.read', 'health_report.read', 'health_risk.read', 'health_plan.read', 'health_plan.write']
const MENTAL_SCOPES = ['mental_checkin.read', 'mental_assessment.read', 'mental_trend.read']
const SERVICE_SCOPES = ['health_service.read', 'health_service.booking.create']

const scopeCopy: Record<string, { title: string; description: string }> = {
  'health_profile.read': { title: '健康档案读取', description: '基础健康信息' }, 'wearable.sleep.read': { title: '睡眠数据读取', description: '睡眠趋势分析' }, 'wearable.exercise.read': { title: '运动数据读取', description: '运动趋势分析' }, 'wearable.heart_rate.read': { title: '心率数据读取', description: '心率趋势分析' }, 'health_report.read': { title: '体检报告读取', description: 'AI 体检解读' }, 'health_risk.read': { title: '健康风险读取', description: '风险评估与建议' }, 'health_plan.read': { title: '健康计划读取', description: '计划分析' }, 'health_plan.write': { title: '健康计划写入', description: '生成个性化计划' }, 'mental_checkin.read': { title: '心理状态读取', description: '情绪、压力与精力趋势' }, 'mental_assessment.read': { title: '心理自评读取', description: '心理健康筛查结果' }, 'mental_trend.read': { title: '心理趋势读取', description: '个人心理变化趋势' }, 'health_service.read': { title: '健康服务读取', description: '查看可用健康服务' }, 'health_service.booking.create': { title: '创建健康服务预约', description: '预约授权验证' },
}
const actorCopy: Record<string, string> = {
  health_supervisor: 'AI 健康助手', health_supervisor_agent: 'AI 健康助手', report_agent: 'AI 体检解读',
  sleep_agent: '睡眠健康助手', risk_agent: '健康风险分析', health_plan_agent: '健康计划助手',
  mental_health_agent: '心理健康助手', service_recommendation: '健康服务推荐', health_service: '健康服务', health_service_agent: '健康服务',
}
const purposeCopy: Record<string, string> = {
  personal_health_analysis: '生成个性化健康建议', report_analysis: '生成 AI 体检解读', sleep_analysis: '分析近期睡眠状态',
  risk_analysis: '进行健康风险分析', health_plan_generation: '生成健康改善计划', mental_health_analysis: '生成心理健康趋势分析',
  service_recommendation: '匹配适合的健康服务', booking_authorization: '健康服务预约授权验证',
  '用于 AI 健康助手个性化建议': '生成个性化健康建议', '用于 AI Report Agent 解读用户指定的体检报告': '生成 AI 体检解读',
}
const outcomeCopy: Record<string, { label: string; color: string }> = { allowed: { label: '已允许', color: 'green' }, denied: { label: '已阻止', color: 'red' }, expired: { label: '已过期', color: 'orange' } }
const scopeDisplay = (scope: string) => scopeCopy[scope]?.title || scope
const consentStatus = (status: DataConsent['status']) => status === 'active' ? { label: '已授权', color: 'green' } : status === 'expired' ? { label: '已过期', color: 'orange' } : { label: '已撤回', color: 'default' }

function ScopeRow({ scope, active, onToggle }: { scope: DataScope; active: boolean; onToggle: () => void }) {
  const copy = scopeCopy[scope.code] || { title: scope.name, description: '健康数据授权' }
  return <div className={`auth-scope-row${scope.sensitive ? ' auth-scope-sensitive' : ''}`}><div className="auth-scope-copy"><b>{copy.title}</b><span>{copy.description}</span><small>{scope.code}</small></div><div className="auth-scope-control"><Tag color={active ? 'green' : 'default'}>{active ? '已授权' : '未授权'}</Tag><Switch checked={active} onChange={onToggle} aria-label={`${copy.title}授权开关`} /></div></div>
}

function AccessLogRow({ item }: { item: AuthorizationAccessLog }) {
  const outcome = outcomeCopy[item.outcome] || { label: item.outcome || '已记录', color: 'blue' }
  const actor = actorCopy[item.actor_id || ''] || actorCopy[item.actor_type] || (item.actor_type === 'user' ? '授权管理' : '系统服务')
  const purpose = purposeCopy[item.purpose || ''] || item.purpose || '授权范围内的数据处理'
  return <div className="audit-row"><div className="audit-icon"><EyeOutlined /></div><div className="audit-copy"><b>{actor}</b><span>访问：{item.scope ? scopeDisplay(item.scope) : item.action}</span><small>用途：{purpose}</small>{item.outcome === 'denied' ? <small className="audit-denied-reason">原因：当前未授权</small> : null}</div><div className="audit-meta"><Tag color={outcome.color}>{outcome.label}</Tag><time>{dayjs(item.created_at).format('MM-DD HH:mm')}</time></div></div>
}

export function DataAuthorization() {
  const [overview, setOverview] = useState<AuthorizationOverview | null>(null); const [scopes, setScopes] = useState<DataScope[]>([]); const [consents, setConsents] = useState<DataConsent[]>([]); const [logs, setLogs] = useState<AuthorizationAccessLog[]>([]); const [approvals, setApprovals] = useState<AgentApproval[]>([]); const [loading, setLoading] = useState(true); const [pendingScope, setPendingScope] = useState<DataScope | null>(null); const [processing, setProcessing] = useState(false)
  const refresh = useCallback(async () => { const [nextOverview, nextScopes, nextConsents, nextLogs, nextApprovals] = await Promise.all([getAuthorizationOverview(), getAuthorizationScopes(), getDataConsents(), getAuthorizationAccessLogs(), getAgentApprovals()]); setOverview(nextOverview); setScopes(nextScopes); setConsents(nextConsents); setLogs(nextLogs); setApprovals(nextApprovals) }, [])
  useEffect(() => { void (async () => { try { await refresh() } catch { message.error('数据授权信息加载失败') } finally { setLoading(false) } })() }, [refresh])
  const activeByScope = useMemo(() => new Map(consents.filter((item) => item.status === 'active').map((item) => [item.scope, item])), [consents]); const activeFor = (scope: string) => activeByScope.has(scope); const scopeRows = (codes: string[]) => scopes.filter((scope) => codes.includes(scope.code)); const pendingApprovals = approvals.filter((item) => item.status === 'pending')
  const authorizationRecords = useMemo(() => scopes.map((scope) => {
    const latest = consents.filter((item) => item.scope === scope.code).sort((a, b) => dayjs(b.granted_at).valueOf() - dayjs(a.granted_at).valueOf())[0]
    const active = activeByScope.get(scope.code)
    return { scope, consent: active || latest || null, active: Boolean(active) }
  }), [activeByScope, consents, scopes])
  const confirmToggle = async () => { if (!pendingScope) return; const consent = activeByScope.get(pendingScope.code); setProcessing(true); try { if (consent) { await revokeDataConsent(consent.id); message.success(`已撤销「${scopeDisplay(pendingScope.code)}」授权，后续访问将立即被拒绝`) } else { await createDataConsent({ grantee_type: pendingScope.category === 'service' ? 'service' : 'agent', grantee_id: pendingScope.sensitive ? 'mental_health_agent' : pendingScope.category === 'service' ? 'health_service_agent' : 'health_supervisor_agent', scope: pendingScope.code, purpose: pendingScope.sensitive ? '用于个人心理健康趋势分析，默认不向企业管理员开放' : pendingScope.category === 'service' ? '用于健康服务推荐与预约确认' : '用于 AI 健康助手的个性化健康建议', expires_at: null }); message.success(`已授权「${scopeDisplay(pendingScope.code)}」`) }; setPendingScope(null); await refresh() } catch (error: any) { message.error(error?.response?.data?.detail || '授权设置失败') } finally { setProcessing(false) } }
  return <section className="data-authorization-page"><div className="authorization-heading"><p>管理你的健康数据访问权限、授权范围与访问记录</p></div><Row gutter={[16, 16]} className="auth-overview"><Col xs={24} sm={12} xl={6}><Card loading={loading} className="auth-overview-card"><Statistic title="当前有效授权" value={overview?.active_scope_count ?? 0} suffix="项" prefix={<SafetyCertificateOutlined />} /></Card></Col><Col xs={24} sm={12} xl={6}><Card loading={loading} className="auth-overview-card"><Statistic title="AI 数据授权" value={overview?.ai_consent_count ?? 0} suffix="项" /></Card></Col><Col xs={24} sm={12} xl={6}><Card loading={loading} className="auth-overview-card"><Statistic title="健康服务授权" value={overview?.service_consent_count ?? 0} suffix="项" /></Card></Col><Col xs={24} sm={12} xl={6}><Card loading={loading} className="auth-overview-card"><Statistic title="最近数据访问" value={overview?.last_access_at ? dayjs(overview.last_access_at).format('今天 HH:mm') : '暂无'} valueStyle={{ fontSize: 20 }} prefix={<ClockCircleOutlined />} /></Card></Col></Row>
    <Card className="auth-card ai-auth-card" title="AI 数据使用授权" extra={<Tag color="green">你可随时撤销</Tag>}><p className="auth-card-description">授权后，AI 健康助手仅在回答当前问题时读取相应范围的数据，不会向企业管理员展示你的原始健康数据。</p><div className="auth-scope-grid">{scopeRows(AI_SCOPES).map((scope) => <ScopeRow key={scope.code} scope={scope} active={activeFor(scope.code)} onToggle={() => setPendingScope(scope)} />)}</div><div className="auth-sensitive-section"><div className="auth-section-divider"><span>敏感数据</span><Tag color="orange">需单独授权</Tag></div><p>心理健康数据仅用于你个人的健康支持建议，默认不向企业管理员开放。</p><div className="auth-scope-grid">{scopeRows(MENTAL_SCOPES).map((scope) => <ScopeRow key={scope.code} scope={{ ...scope, sensitive: true }} active={activeFor(scope.code)} onToggle={() => setPendingScope(scope)} />)}</div></div></Card>
    <Row gutter={[16, 16]} className="authorization-two-column"><Col xs={24} xl={12}><Card className="auth-card" title="企业数据使用"><div className="enterprise-permissions"><p><CheckCircleFilled /> 匿名聚合统计</p><p><CheckCircleFilled /> 企业整体健康趋势</p><p className="unavailable">× 个人体检明细</p><p className="unavailable">× 心理健康明细</p><p className="unavailable">× AI 聊天内容</p></div><Alert className="auth-enterprise-note" type="info" showIcon message="企业管理员默认仅可查看匿名或聚合数据，不能查看员工个人敏感健康明细。" /></Card></Col><Col xs={24} xl={12}><Card className="auth-card" title="健康服务授权"><p className="auth-card-description">预约健康服务前会请求你的确认，系统不会在未授权时替你创建预约。</p><div className="auth-scope-list">{scopeRows(SERVICE_SCOPES).map((scope) => <ScopeRow key={scope.code} scope={scope} active={activeFor(scope.code)} onToggle={() => setPendingScope(scope)} />)}</div>{pendingApprovals.length ? <div className="pending-approvals"><b>待确认操作</b><List size="small" dataSource={pendingApprovals.slice(0, 2)} renderItem={(item) => <List.Item><Text>{item.action_type}</Text><Text type="secondary">{dayjs(item.requested_at).format('MM-DD HH:mm')}</Text></List.Item>} /></div> : <div className="auth-empty-inline">暂无待确认的健康服务操作</div>}</Card></Col></Row>
    <Row gutter={[16, 16]} className="authorization-two-column authorization-records"><Col xs={24} xl={11}><Card className="auth-card auth-list-card" title="我的授权记录" extra={<span className="auth-record-count">全部 {authorizationRecords.length} 项</span>}>{authorizationRecords.length ? <List className="consent-list authorization-record-list" dataSource={authorizationRecords} renderItem={({ scope, consent, active }) => { const status = active ? { label: '已授权', color: 'green' } : consent ? consentStatus(consent.status) : { label: '未授权', color: 'default' }; return <List.Item actions={active ? [<Button key="revoke" danger type="link" icon={<StopOutlined />} onClick={() => setPendingScope(scope)}>撤回</Button>] : []}><div className="consent-record"><div><b>{scopeDisplay(scope.code)}</b><Tag color={status.color}>{status.label}</Tag></div><span>授权对象：{consent?.grantee_type === 'service' || scope.category === 'service' ? '健康服务' : scope.sensitive ? '心理健康助手' : 'AI 健康助手'}</span><span>用途：{consent?.purpose || scopeCopy[scope.code]?.description || '尚未启用该数据授权'}</span><small>{consent ? `${consent.status === 'revoked' ? '撤回' : '授权'}时间：${dayjs(consent.status === 'revoked' ? consent.revoked_at : consent.granted_at).format('YYYY-MM-DD HH:mm')}` : '当前未授权'} · {scope.code}</small></div></List.Item> }} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无可配置授权范围" />}</Card></Col><Col xs={24} xl={13}><Card className="auth-card auth-list-card" title={<div className="audit-card-title"><b>数据访问记录</b><small>这里记录你的健康数据何时、因何目的被系统或 AI 使用。</small></div>} extra={<Button type="link">查看全部访问记录 →</Button>}>{logs.length ? <div className="audit-list">{logs.slice(0, 6).map((item) => <AccessLogRow key={item.id} item={item} />)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据访问记录" />}</Card></Col></Row>
    <Modal open={Boolean(pendingScope)} title={activeByScope.get(pendingScope?.code || '') ? '确认撤销数据授权' : '确认授予数据授权'} okText={activeByScope.get(pendingScope?.code || '') ? '确认撤销' : '确认授权'} okButtonProps={{ danger: Boolean(activeByScope.get(pendingScope?.code || '')), loading: processing }} cancelText="取消" onCancel={() => !processing && setPendingScope(null)} onOk={() => void confirmToggle()}>{pendingScope && <div className="auth-confirm"><LockOutlined /><div><b>{scopeDisplay(pendingScope.code)}</b><p>{activeByScope.get(pendingScope.code) ? '撤销后，相关 Agent 或服务将立即无法再读取该范围的数据。' : '系统将仅在你选择的 Agent 或服务执行本次用途时访问该范围的数据。'}</p></div></div>}</Modal>
  </section>
}
