class McpError(Exception):
    """Safe MCP boundary error exposing only a stable code."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


MCP_CONFIG_INVALID = "MCP_CONFIG_INVALID"
MCP_TRANSPORT_UNSUPPORTED = "MCP_TRANSPORT_UNSUPPORTED"
MCP_CREDENTIAL_MISSING = "MCP_CREDENTIAL_MISSING"
MCP_SERVER_CONNECT_FAILED = "MCP_SERVER_CONNECT_FAILED"
MCP_LIST_TOOLS_FAILED = "MCP_LIST_TOOLS_FAILED"
MCP_TOOL_SCHEMA_INVALID = "MCP_TOOL_SCHEMA_INVALID"
MCP_TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
MCP_TOOL_ARGUMENTS_INVALID = "MCP_TOOL_ARGUMENTS_INVALID"
MCP_TOOL_EXECUTION_FAILED = "MCP_TOOL_EXECUTION_FAILED"
MCP_TOOL_EMPTY_RESULT = "MCP_TOOL_EMPTY_RESULT"
MCP_HTTP_URL_INVALID = "MCP_HTTP_URL_INVALID"
MCP_HTTP_PRIVATE_ADDRESS_FORBIDDEN = "MCP_HTTP_PRIVATE_ADDRESS_FORBIDDEN"
MCP_HTTP_HOST_RESOLUTION_FAILED = "MCP_HTTP_HOST_RESOLUTION_FAILED"
MCP_HTTP_CONNECT_FAILED = "MCP_HTTP_CONNECT_FAILED"
MCP_HTTP_TIMEOUT = "MCP_HTTP_TIMEOUT"
MCP_HTTP_TLS_FAILED = "MCP_HTTP_TLS_FAILED"
